-- Migration: realtime_publication (slice 1b, issue #9)
--
-- Enable Supabase Realtime (Postgres Changes) DELIVERY for the social tables. The
-- `reactions`/`comments` table schema is unchanged (#7) — this only adds them to
-- the `supabase_realtime` logical-replication publication so INSERT/UPDATE/DELETE
-- events are actually emitted to subscribed clients. Without this, the board's
-- live push is a no-op (the client subscribes successfully but never receives a
-- change), which is exactly the gap this closes.
--
-- Security (per the non-author security review of #9):
--   * Both tables have RLS ENABLED + FORCED (#7). Realtime authorizes Postgres
--     Changes against those same RLS policies via the user's token, so a client
--     only ever receives rows for its own household — adding them to the
--     publication does NOT widen exposure beyond what SELECT already allows.
--   * Replica identity: this migration originally KEPT the DEFAULT (primary key
--     only) as a data-minimization choice. That was WRONG for DELETE and is
--     corrected in a later migration (20260721194820, issue #63): the board
--     subscribes with a `household_id=eq.<id>` filter and the RLS SELECT policies
--     are household-scoped, but a DELETE change image under DEFAULT identity
--     carries only the PK — no `household_id` — so Realtime's filter + RLS both
--     miss and the DELETE (un-react / comment delete) is dropped. The fix sets
--     `replica identity full` on both tables so DELETE carries the full old row.
--     It does NOT widen exposure: Realtime still authorizes every row against the
--     same household-scoped RLS. For these tiny, low-churn tables the extra
--     streamed columns are negligible. (Kept here as a comment-only correction;
--     the ALTERs live in the #63 migration, not this already-applied one.)
--
-- `supabase_realtime` is created by the Supabase platform/local stack; add the
-- two tables to it. Idempotent across a clean `supabase db reset` (the
-- publication starts empty of these tables, so the ADD is a one-time effect).
alter publication supabase_realtime add table public.reactions, public.comments;
